#!/usr/bin/env python

import sys

from src import auto
from src import template_params

def main():
    mods = dict(
        type=template_params,
        auto=auto
    )

    if len(sys.argv) > 1:
        to_run = [mods[sys.argv[1]]]
    else:
        to_run = mods.values()

    for mod in to_run:
        mod.run()

if __name__ == '__main__':
    main()
